[package]
name = "my_rust"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "1"
rust-crypto = "0.2.36"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
unicode-segmentation = "1.9.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "my_benchmark"
harness = false
